### ISSUE TITLE
Put ADTS segments into MP4 container

### ISSUE THREAD

**Issue by Sorrow446** [abema/go-mp4#103]
Hello. I'd like to put a bunch of AAC files in ADTS containers into an MP4 container without the need of FFmpeg. Is it possible to do so with this library?

https://i.imgur.com/NULdkrV.png

したいなら、日本語でお返事ください。

**Comment by sunfish-shogi** [comment]
Sorry for late reply.

go-mp4 has only features to read/write mp4 container layer and has no codecs.
If you need container convert or transcode, you should integrate with other library or your own codes.
