### ISSUE TITLE
Screenshot support

### ISSUE THREAD

**Issue by songjiayang** [abema/go-mp4#114]
Can we use go-mp4 for screenshot with specific timestamp.

**Comment by sunfish-shogi** [comment]
Does "screenshot" means images extracted from a video frames?

By go-mp4, you can extract mdat(media data) box which contains video frames.
However, go-mp4 has no codec implementation.
So, if you want to extract a specific video frame as image file, you should use any codec library.

**Comment by songjiayang** [comment]
> 

make sense,  thanks
