### ISSUE TITLE
How to implement webvtt/vttc

### ISSUE THREAD

**Issue by mattetti** [abema/go-mp4#127]
I'm curious about implementing Webvtt with vttc support. In a fragmented text MP4 file, the webvtt content is split across multiple atoms. We need to read data across 3 (?) atoms that aren't nested (one indicating we need to look at the mdata), one with the timestamp and finally one or more mdata for the cue (sharing the previously mentioned timestamp).

It looks like reflection wouldn't work for such an approach since we need to reach out to previously parsed data but maybe I am wrong? After all, I'm just a hobbyist.

**Comment by sunfish-shogi** [comment]
Sorry, I have never read standard of vttc box yet, so I'm not familiar with it.
I create this library in compliance with ISO Base Media File Format, but I don't know all of derived standards.
I can answer about usage of go-mp4's interface.

**Comment by sunfish-shogi** [comment]
### about not supported box type

If you want to parse unsupported box with reflection, you can add new definition as user-defined box like https://github.com/abema/go-mp4#user-defined-boxes.

If you want to get only box's offset, you can use ExtractBox(es) or ReadBoxStructure.

### general flow for parsing fragmented MP4

I hope following sample code will be helpful.

```go
  _, err = mp4.ReadBoxStructure(r, func(h *mp4.ReadHandle) (interface{}, error) { 
    switch h.Path[0] { 

    case mp4.BoxTypeMoov():
      // do anything for initilization segment

    case mp4.BoxTypeMoof():
      // example: extract tfdt box
      tfdts, err := mp4.ExtractBoxWithPayload(r, &h.BoxInfo, mp4.BoxPath{mp4.BoxTypeTraf(), mp4.BoxTypeTfdt()})
      if err != nil { 
        return nil, err
      } 
      if len(tfdts) == 0 { 
        return nil, errors.New("tfdt box not found")
      } 
      tfdt := tfdts[0].Payload.(*mp4.Tfdt)

      // example: extract tfhd box
      tfhds, err := mp4.ExtractBoxWithPayload(r, &h.BoxInfo, mp4.BoxPath{mp4.BoxTypeTraf(), mp4.BoxTypeTfhd()})
      if err != nil { 
        return nil, err
      } 
      if len(tfhds) == 0 { 
        return nil, errors.New("tfdt box not found")
      } 
      tfhd := tfhds[0].Payload.(*mp4.Tfhd)

      println("---------- fragment ----------")
      println("track id              :", tfhd.TrackID)
      println("base media decode time:", tfdt.GetBaseMediaDecodeTime())

    case mp4.BoxTypeMdat():
      println("mdat size             :", h.BoxInfo.Size)

      // if you want to read mdat payload...
      //   buf := bytes.NewBuffer(nil)
      //   _, err := h.ReadData(buf)

    } 
    return nil, nil
  })
  if err != nil { 
    panic(err)
  } 
```
