### ISSUE TITLE
Split box_types.go into multiple files

### ISSUE THREAD

**Issue by aler9** [abema/go-mp4#139]
Hello @sunfish-shogi, i'm about to contribute AV1 boxes, but i have a style-related doubt: the `box_types.go` file is getting huge and it's about to become even bigger in the future. This adds a degree of difficulty to all maintenance operations, i.e. finding boxes, adding boxes and keeping everything ordered.

In my opinion, the file should be splitted into multiple ones by using some criterion, for instance:

* by specification (my choice), for instance:

   box_types_iso_14496_12.go
   box_types_iso_14496_14.go
   box_types_metadata.go
   box_types_other.go

* by starting letter:

   box_types_a.go
   box_types_b.go

* by single box. This would be optimal and doesn't cause any performance issue in go (see my library [gomavlib](https://github.com/bluenviron/gomavlib/tree/main/pkg/dialects/common)) but it may be better to perform the operation in a dedicated folder, and this would break compatibility with the existing API:

  box_type_btrt.go
  box_type_colr.go

Regardless of the criterion, this is in my opinion a good way to improve maintainability of the library.

**Comment by sunfish-shogi** [comment]
@aler9 
Thank you for your suggestion!

> by specification (my choice), for instance:
> box_types_iso_14496_12.go
> box_types_iso_14496_14.go
> box_types_metadata.go
> box_types_other.go

I think by-specification division rule is good.
I will create a pull request for that.

As a side note, go-mp4 had initially by-single-box files in root directory.

**Comment by aler9** [comment]
Fixed by #140
