### ISSUE TITLE
Is it possible to use the library to concatenate AAC fragments into a single MP4 file?

### ISSUE THREAD

**Issue by laurento** [abema/go-mp4#155]
I'm trying to understand if your library can be used to concatenate a number or AAC audio fragments into one single mp4 audio file without using external binaries (e.g. ffmpeg).

Do you happen to have a code snippet to demonstrate such use-case?

**Comment by sunfish-shogi** [comment]
> Do you happen to have a code snippet to demonstrate such use-case?

Sorry, I have no sample code for this use-case so far.

go-mp4 supports only low-level MP4 box structure parsing or editing.
So, this library is not suitable for complex box structure conversion.

**Comment by laurento** [comment]
Many thanks for your prompt reply. Keep up the good work!
