### ISSUE TITLE
Could you give an example on how to write create a MP4 file

### ISSUE THREAD

**Issue by krasi-georgiev** [abema/go-mp4#53]
I am reading a h264 stream from a IP camera and need to write it to a file. Can you provide a simple example how to write a MP4 file from h264 nalus.
Thanks!

**Comment by sunfish-shogi** [comment]
I'm not familiar with IP camera and H.264 NAL Unit.
But I think IP camera uses some sort of container (ex. MPEG2-TS) to transfer on IP network.
So dose this question mean you want to convert from other container to MP4 or fMP4 (CMAF) ?
In this use case, I recommend to use some packaging solution, for example Wowza, AWS MediaServices, and FFmpeg.

**Comment by krasi-georgiev** [comment]
actually don't worry I manager to add the required file headers so all good, thanks for the comments

**Comment by zt1983811** [comment]
@krasi-georgiev I am run in to the similar step. Do you mind to show in code how do you manage to convert  h264 stream to one mp4 file please? Thanks in advance !

**Comment by krasi-georgiev** [comment]
It was long time ago so don't remember

**Comment by cedricve** [comment]
Interested in this as well!
