### ISSUE TITLE
Problem of stringifying fixed-point numbers

### ISSUE THREAD

**Issue by haruyama** [abema/go-mp4#54]
https://github.com/abema/go-mp4/blob/04634da10f801e05e3b0166090a8659d39b4732d/box_types_test.go#L710

```go
src: &Mvhd{
...
				Rate:               -0x01234567,
...
				0xfe, 0xdc, 0xba, 0x99, // rate
...
				`Rate=-291.27112 ` +
```

The result of stringifying -0x01234567 (0xfedcba99) shoud be "-291.27110" (in case of prec: 5).

Here are some results of strconv.FormatFloat()
```
gore> a:= float64(int32(-0x01234567)) / (1 << 16)
-291.271103
gore> strconv.FormatFloat(a, 'f', -1, 32)
"-291.27112"
gore> strconv.FormatFloat(a, 'f', -1, 64)
"-291.27110290527344"
gore> strconv.FormatFloat(a, 'f', 5, 64)
"-291.27110"
```

Tkhd.{Width,Height} may have same problem.

**Comment by haruyama** [comment]
Since the precision of 16-bit decimal part is about 0.00003, setting 4 to prec parameter of strconv.FormatFloat() (https://golang.org/pkg/strconv/#FormatFloat) would be appropriate.

```
gore> strconv.FormatFloat(a, 'f', 4, 32)
"-291.2711"
```

**Comment by sunfish-shogi** [comment]
Thank you for your bug report!

I think that the problem is I mistaked the value of bitSize argument of FormatFloat function.
mvhd.GetRate(), tkhd.GetWidth() and tkhd.GetHeight() convert fixed-point number to 64bits floating point number, but I have set 32 to bitSize argument.
So, I'm thinking to fix the bitSize to 64 as following.
https://github.com/abema/go-mp4/pull/55/files#diff-e829ad2c828be949e9bc1b31826201d892b5be1afe6ce6327e916a4301daf748R850
What do you think about it?

**Comment by haruyama** [comment]
I agree with the adoption of bitSize=64.

Since fixed-point (16, 16) decimals have a coarser precision than float64 in [-32768.0, 32768.0),
I suppose that prec=4 or prec=5 would be appropriate.

[fix16_to_str()](https://github.com/WeAreROLI/libfixmath/blob/master/libfixmath/fix16_str.c#L28) in [libfixmath](https://code.google.com/archive/p/libfixmath/) seems to return at most 5 decimals.

```c
#include <stdio.h>

#include "fix16.h"

int main() {
  char buf[13];
  fix16_t a = (fix16_t)(-0x01234567);
  fix16_to_str(a, buf, 4);
  printf("prec 4: %s\n", buf);
  fix16_to_str(a, buf, 5);
  printf("prec 5: %s\n", buf);
  fix16_to_str(a, buf, 6);
  printf("prec 6: %s\n", buf);
  fix16_to_str(a, buf, 7);
  printf("prec 7: %s\n", buf);

  return 0;
}
```

```
% ./test
prec 4: -291.2711
prec 5: -291.27110
prec 6: -291.27110
prec 7: -291.27110
```

**Comment by sunfish-shogi** [comment]
Thank you for your suggestions.

I created FormatSignedFixedFloat1616() and  FormatUnsignedFixedFloat1616() in util package.
These functions output with prec=5 for non-integer value and without after the decimal point for integer value.
https://github.com/abema/go-mp4/pull/55/commits/750b7093f4e83c6475c4902fdb89fd02200ef791

**Comment by haruyama** [comment]
Thank you for your swift response.
