### ISSUE TITLE
Question about release plans

### ISSUE THREAD

**Issue by justinruggles** [abema/go-mp4#93]
The API additions since the last release (v0.5.0) are very useful in a project I'm working on. Is there any timeline for releasing those changes?

**Comment by sunfish-shogi** [comment]
I had considering whether including alpha version of new CLI command `mp4tool-fragment` into next release.
But that seems to take time, so I will create new release from current latest revision of master soon.

**Comment by sunfish-shogi** [comment]
I created the new release tag `v0.6.0`.
https://github.com/abema/go-mp4/releases/tag/v0.6.0

**Comment by justinruggles** [comment]
thank you!
